INSERT INTO roles(name) VALUES ('Admin'), ('Projections'), ('Employee');

INSERT INTO users(username, password, role, employee_id) VALUES
('admin', '1234', 1, NULL);

INSERT INTO theaters (name, no_of_rows, seats_per_row) VALUES
('Theater 1', 14, 20),('Theater 2', 8, 12),('Theater 3', 8, 6);

INSERT INTO screenings (movie_id, theater_id, start_time)
VALUES (1, 1, '2019-06-20 18:30'), (2, 2, '2019-06-20 19:00'),(3, 3, '2019-06-20 18:45');

INSERT INTO technologies (name) VALUES ('3D'), ('Dolby Atmos');

INSERT INTO movies(title, runtime, synopsis, genre, language, subtitles, trailer_link, release_date, cast, director, age_restriction, poster) VALUES
('The Matrix', 136, 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers. ', 'Action, Sci-Fi', 'English', 'Danish', 'vKQi3bBA1y8', DATE('1999-03-31'), 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'The Wachowski Brothers', 'R', 'http://www.freemovieposters.net/posters/matrix_the_1999_3131_poster.jpg'),
('Memento', 113, 'A man with short-term memory loss attempts to track down his wife\'s murderer.', 'Mystery, Thriller', 'English', 'Danish', 'UFuFFdK7i44', DATE('2001-05-25'), 'Guy Pearce, Carrie-Anne Moss, Joe Pantoliano', 'Christopher Nolan', 'R', 'https://kadreview.files.wordpress.com/2013/03/memento.jpg'),
('Fight Club', 139, 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.', 'Drama', 'English', 'Danish', 'qtRKdVHc-cE', DATE('1999-10-15'), 'Brad Pitt, Edward Norton, Helena Bonham Carter', 'David Fincher', 'R', 'https://i.jeded.com/i/fight-club.25541.jpg'),
('Primer', 77, 'Four friends/fledgling entrepreneurs, knowing that there\'s something bigger and more innovative than the different error-checking devices they\'ve built, wrestle over their new invention.', 'Drama, Sci-Fi, Thriller', 'English', 'Danish', '-vD-yj9o664', DATE('2004-01-16'), 'Shane Carruth, David Sullivan, Casey Gooden', 'Shane Carruth', 'PG-13', 'https://khfilm.files.wordpress.com/2014/12/primer-poster-1.jpg'),
('Donnie Darko', 113, 'A troubled teenager is plagued by visions of a man in a large rabbit suit who manipulates him to commit a series of crimes, after he narrowly escapes a bizarre accident.', 'Drama, Sci-Fi, Thriller', 'English', 'Danish', 'rPeGaos7DB4', DATE('2001-10-26'), 'Jake Gyllenhaal, Jena Malone, Mary McDonnell', 'Richard Kelly', 'R', 'https://cinefilles.files.wordpress.com/2013/03/donnie-darko-poster-1.jpg'),
('Snatch', 102, 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.', 'Comedy, Crime', 'English', 'Danish', 'ni4tEtuTccc', DATE('2001-01-19'), 'Jason Statham, Brad Pitt, Benicio Del Toro', 'Guy Ritchie', 'R', 'https://i.pinimg.com/originals/39/0e/ef/390eeffb7674f33451710febb18eb30d.jpg'),
('The Shawshank Redemption', 142, 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Drama', 'English', 'Danish', 'NmzuHjWmXOc', DATE('1994-10-14'), 'Tim Robbins, Morgan Freeman, Bob Gunton', 'Frank Darabont', 'R', 'http://www.cinemasterpieces.com/72013/shawmay13.jpg'),
('Office Space', 89, 'Three company workers who hate their jobs decide to rebel against their greedy boss.', 'Comedy', 'English', 'Danish', '3_fG_zLbBeU', DATE('1999-02-19'), 'Ron Livingston, Jennifer Aniston, David Herman', 'Mike Judge', 'R', 'http://www.cinemasterpieces.com/officespacebusstop.jpg'),
('The Dark Knight', 152, 'When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'Action, Crime, Drama', 'English', 'Danish', 'EXeTwQWrcwY', DATE('2008-07-18'), 'Christian Bale, Heath Ledger, Aaron Eckhart', 'Christopher Nolan', 'R', 'http://media.whysoserious.com/201949id1.jpg'),
('Pulp Fiction', 154, 'The lives of two mob hitmen, a boxer, a gangster & his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'Crime, Drama', 'English', 'Danish', '5ZAhzsi1ybM', DATE('1994-10-14'), 'John Travolta, Uma Thurman, Samuel L. Jackson', 'Quention Tarantino', 'R', 'https://debbimacktoo.files.wordpress.com/2016/05/pulpfiction_poster.jpeg'),
('Se7en', 127, 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', 'Crime, Drama, Mystery', 'English', 'Danish', 'znmZoVkCjpI', DATE('1995-09-22'), 'Morgan Freeman, Brad Pitt, Kevin Spacey', 'David Fincher', 'R', 'http://image.tmdb.org/t/p/original/yvDMAP4SI25eeMzScWikqqrbXdM.jpg'),
('The Silence of the Lambs', 118, 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', 'Crime, Drama, Thriller', 'English', 'Danish', 'W6Mm8Sbe__o', DATE('1991-02-14'), 'Jodie Foster, Anthony Hopkins, Lawrence A. Bonney', 'Jonathan Demme', 'R', 'http://posterwire.com/wp-content/uploads/silence_of_the_lambs.jpg'),
('American History X', 119, 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.', 'Drama', 'English', 'Danish', 'XfQYHqsiN5g', DATE('1998-11-20'), 'Edward Norton, Edward Furlong, Beverly D\'Angelo', 'Tony Kaye', 'R', 'http://images6.fanpop.com/image/photos/38800000/American-History-X-Poster-american-history-x-38821277-1024-1200.jpg'),
('The Usual Suspects', 106, 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.', 'Crime, Mystery, Thriller', 'English', 'Danish', 'Q0eCiCinc4E', DATE('1995-09-15'), 'Kevin Spacey, Gabriel Byrne, Chazz Palminteri', 'Bryan Singer', 'R', 'http://www.cinemasterpieces.com/62014/bv131.jpg'),
('The Departed', 151, 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 'Crime, Drama, Thriller', 'English', 'Danish', 'iojhqm0JTW4', DATE('2006-08-06'), 'Leonardo DiCaprio, Matt Damon, Jack Nicholson', 'Martin Scorsese', 'R', 'http://movieposters.2038.net/p/Departed,-The.jpg'),
('The 25th Hour', 135, 'Cornered by the DEA, convicted New York drug dealer Montgomery Brogan reevaluates his life in the 24 remaining hours before facing a seven-year jail term.', 'Drama', 'English', 'Danish', '2qZVGJd6-rI', DATE('2002-12-16'), 'Edward Norton, Rosario Dawson, Philip Seymour Hoffman', 'Spike Lee', 'R', 'https://s.newsweek.com/sites/www.newsweek.com/files/styles/full/public/2017/09/11/edward-norton-and-spike-lee-25th-hour-movie.jpg'),
('Honogurai Mizu No Soko Kara', 101, 'A mother and her 6 year old daughter move into a creepy apartment whose every surface is permeated by water.', 'Drama, Horror, Mystery', 'Japanese', 'English', 'dpIVoUczCuc', DATE('2002-01-19'), 'Hitomi Kuroki, Rio Kanno, Mirei Oguchi', 'Hideo Nakata', 'PG-13', 'https://static.kino.de/wp-content/gallery/honogurai-mizu-no-soko-kara-2001/dark-water-3-rcm0x1920u.jpg'),
('John Wick - Parabellum', 131, 'Super-assassin John Wick is on the run after killing a member of the international assassin\'s guild, and with a $14 million price tag on his head - he is the target of hit men and women everywhere.', 'Action, Crime, Thriller', 'English', 'Danish', 'pU8-7BX9uxs&t=2s', DATE('2019-04-17'), 'Keanu Reeves, Halle Berry, Ian McShane', 'Chad Stahelski', 'R', 'https://m.media-amazon.com/images/M/MV5BMDg2YzI0ODctYjliMy00NTU0LTkxODYtYTNkNjQwMzVmOTcxXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SY1000_CR0,0,648,1000_AL_.jpg'),
('Avengers - Endgame', 181, 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to undo Thanos\' actions and restore order to the universe.', 'Action, Adventure, Sci-Fi', 'English', 'Danish', 'TcMBFSGVi1c', DATE('2019-04-26'), 'Robert Downey Jr., Chris Evans, Mark Ruffalo', 'Anthony Russo, Joe Russo', 'PG-13', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SY1000_CR0,0,674,1000_AL_.jpg'),
('A Dog\'s Journey', 109, 'A dog finds the meaning of his own existence through the lives of the humans he meets.', 'Adventure, Comedy, Drama', 'English', 'Danish', 'A2FrrSyyKfA', DATE('2019-05-17'), 'Josh Gad, Dennis Quaid, Kathryn Prescott', 'Gail Mancuso', 'PG', 'https://m.media-amazon.com/images/M/MV5BYjRhMWY0ODMtMmM3OC00ZGRmLWIyZjktZGQ0ZGE4MzcyZWE5XkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SY1000_CR0,0,631,1000_AL_.jpg'),
('Godzilla - King of the Monsters', 131, 'The crypto-zoological agency Monarch faces off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah.', 'Action, Adventure, Fantasy, Sci-Fi', 'English', 'Danish', 'QFxN2oDKk0E', DATE('2019-05-31'), 'Kyle Chandler, Vera Farmiga, Millie Bobby Brown', 'Michael Dougherty', 'PG-13', 'https://m.media-amazon.com/images/M/MV5BOGFjYWNkMTMtMTg1ZC00Y2I4LTg0ZTYtN2ZlMzI4MGQwNzg4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg'),
('Men in Black - International', 115, 'The Men in Black have always protected the Earth from the scum of the universe. In this new adventure, they tackle their biggest threat to date: a mole in the Men in Black organization.', 'Action, Comedy, Sci-Fi', 'English', 'Danish', 'BV-WEb2oxLk', DATE('2019-06-14'), 'Chris Hemsworth, Emma Thompson, Tessa Thompson', 'F. Gary Gray', 'PG-13', 'https://m.media-amazon.com/images/M/MV5BZTBmZGNiNGEtZmIxYy00NDgxLWE4MGItYzkwYjg2YzQ1Nzk1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg'),
('Toy Story 4', 89, 'When a new toy called "Forky" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.', 'Animation, Adventure, Comedy, Family, Fantasy', 'English', 'Danish', 'wmiIUN-7qhE', DATE('2019-06-21'), 'Keanu Reeves, Christina Hendricks, Tom Hanks', 'Josh Cooley', 'G', 'https://m.media-amazon.com/images/M/MV5BMTYzMDM4NzkxOV5BMl5BanBnXkFtZTgwNzM1Mzg2NzM@._V1_SY1000_CR0,0,674,1000_AL_.jpg')